# **Exercises XP**

# **Create a 1D NumPy array containing numbers from 0 to 9.**

In [ ]:
!pip install numpy

In [ ]:
import numpy as np

In [ ]:
array1=np.array([0,1,2,3,4,5,6,7,8,9])
array1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# **Convert a list [3.14, 2.17, 0, 1, 2] into a NumPy array and convert its data type to integer.**

In [ ]:
array2=np.array([3.14, 2.17, 0, 1, 2])
array2=array2.astype(int)
array2


array([3, 2, 0, 1, 2])

# **Create a 3x3 NumPy array with values ranging from 1 to 9.**

In [ ]:
array=np.array([[1,2,3],[4,5,6],[7,8,9]])
array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# **Create a 2D NumPy array of shape (4, 5) filled with random numbers.**

In [ ]:
array=np.random.rand(4,5)
array

array([[0.95467074, 0.49384158, 0.82513817, 0.6588225 , 0.12812811],
       [0.73455304, 0.97169846, 0.50778494, 0.92831482, 0.42756241],
       [0.68286057, 0.61251201, 0.79547815, 0.1416146 , 0.10674726],
       [0.36349802, 0.27195971, 0.79936358, 0.11464562, 0.93317079]])

# **Select the second row from a given 2D NumPy array.**



In [ ]:
array = np.array([[21,22,23,22,22],[20, 21, 22, 23, 24],[21,22,23,22,22]])
array[1]

array([20, 21, 22, 23, 24])

# **Reverse the order of elements in a given 1D NumPy array (first element becomes last).**

In [ ]:
array1=np.array([0,1,2,3,4,5,6,7,8,9])
array1=array1[::-1]
array1


array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

# **Create a 4x4 identity matrix using NumPy.**

In [ ]:
#array of ceros
array2=np.zeros((4,4))
array2

for i in range(4):
  for j in range(4):
    if i==j:
      array2[i][j]=1

array2


array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

# **Find the sum and average of a given 1D array.**

In [ ]:
array=np.array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])
print(array.sum())
print(array.mean())

45
4.5


# **Create a NumPy array with elements from 1 to 20; then reshape it into a 4x5 matrix.**

In [ ]:
array=np.array([])
for i in range(1,21):
  array=np.append(array,i)

array=array.astype(int)

array=array.reshape(4,5)
array


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

# **Extract all odd numbers from a given NumPy array.**

In [ ]:
array=np.array([ 1,  2,  3,  4,  5])

array2=np.array([])
for x in range(len(array)+1):
  if x % 2 != 0:
    array2=np.append(array2,x)

print(array2.astype(int))

[1 3 5]
