In [ ]:
!pip install numpy

In [ ]:
import numpy as np

In [ ]:
import numpy as np

# Creating a 1D NumPy array
array_1d = np.array([1, 2, 3, 4])
print("1D Array:", array_1d)  # Expected Output: 1D Array: [1 2 3 4]

# Creating a 2D NumPy array
array_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("2D Array:\n", array_2d)
# Expected Output:
# 2D Array:
# [[1 2 3]
#  [4 5 6]]

# Array attributes
print("Shape:", array_2d.shape)  # Expected Output: Shape: (2, 3) - 2 rows and 3 columns
print("Size:", array_2d.size)   # Expected Output: Size: 6 - Total 6 elements
print("Data Type:", array_2d.dtype)  # Expected Output: Data Type: int64 (or similar, depending on system)

1D Array: [1 2 3 4]
2D Array:
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Size: 6
Data Type: int64


In [ ]:
# Exercise: Create the following arrays:
# A one dimensional array with the temperatures from this week.
# A two dimensional array of shape 2,5 with random values (choose them yourself) from 1 to 10.
# A 3D array with valid pixel values for a picture with 9 pixels.

array1= np.array([20,15,10,15])

array2= np.array([[1, 2, 3], [4, 5, 6]])

array3 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

In [ ]:
import numpy as np

# Example 2D array
array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Accessing a single element
print("Element at row 1, column 2:", array_2d[1, 2])  # Output: 6

# Accessing a row
print("Second row:", array_2d[1, :])  # Output: [4 5 6]

# Accessing a column
print("Third column:", array_2d[:, 2])  # Output: [3 6 9]

Element at row 1, column 2: 6
Second row: [4 5 6]
Third column: [3 6 9]


In [ ]:
import numpy as np

# Example 2D array
array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Slicing a portion of the array
print("Slice of the array:", array_2d[0:2, 1:3])  # Output: [[2 3] [5 6]]

Slice of the array: [[2 3]
 [5 6]]


In [ ]:
import numpy as np

# Example array
array = np.array([[1, 2], [3, 4], [5, 6]])

# Boolean indexing
result = array[array > 3]
print("Result of Boolean Indexing:", result)  # Output: [4 5 6], a 1D array

Result of Boolean Indexing: [4 5 6]


In [ ]:
import numpy as np

# Creating a sample array
array = np.array([10, 20, 30, 40, 50])

# Indexing (accessing a single element)
print("First element:", array[0])

# Slicing (accessing multiple elements)
print("First three elements:", array[:3])

First element: 10
First three elements: [10 20 30]


In [ ]:
# Boolean indexing
print("Elements greater than 25:", array[array > 25])

# Fancy indexing (using a list of indices)
print("Select specific elements:", array[[1, 3]])

Elements greater than 25: [30 40 50]
Select specific elements: [20 40]


In [ ]:
# 1. Basic Indexing: Create an array of 10 elements and access the 5th element in it.

# 2. Basic Slicing: From the same array, extract a slice containing the 3rd to the 8th elements.

# 3. Boolean Indexing: Create an array of 6 random integers between 10 and 50. Print the elements that are greater than 30.

# 4. Fancy Indexing: From the same array, use fancy indexing to access the 2nd, 4th, and 6th elements.

# Expected Output:

# The 5th element of the first array.
# A slice of the array showing elements from the 3rd to the 8th position.
# Elements greater than 30 from the random array.
# Selected elements (2nd, 4th, 6th) from the random array using fancy indexing.




In [ ]:
rand = np.random.randint(10, 50, 6)
print(rand[rand>30])

[38 37 39]


In [ ]:
x = np.array([1, 2, 3, 4, 5, 6, 7])
new = np.random.permutation(x)
new

array([7, 5, 3, 1, 6, 4, 2])

In [ ]:
two = np.array([[1,2], [3,4], [5,6]])
np.random.permutation(two)

array([[3, 4],
       [1, 2],
       [5, 6]])

In [ ]:
arr = np.array([1, 2, 3, 4, 5])
arr[2] = 10  # Changing the third element
print(arr)  # Output: [1, 2, 10, 4, 5]

[ 1  2 10  4  5]


In [ ]:
# Exercise:
# After learning about array indexing and slicing, it's important to practice these concepts. Here are some exercises to help solidify your understanding:

# 1. Modifying Specific Elements:

# Create an array with values from 1 to 10. Change the value of the fifth element to 50.

# 2. Slicing and Modifying a Range:

# Given an array of 10 elements, modify the elements from index 3 to 7 to be their negative equivalent.

# 3. Conditional Modification with Boolean Indexing:

# Create an array with 20 random integers between 1 and 100. Set all values greater than 50 to -1.

# 4. Advanced Indexing Modification:

# Given a 2D array of shape (5, 5), modify the elements in the diagonal to be twice their original value.

# 5. Understanding Slicing Impact:

# Create an array of 10 elements. Slice the array from index 2 to 5, and modify the first element of the slice. Observe the change in the original array.

In [ ]:
ar_z= np.zeros(5)
ar_z

array([0., 0., 0., 0., 0.])

In [ ]:
ar_1=np.ones(8)
ar_1

array([1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
import numpy as np

# Creating sample arrays
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Element-wise addition
print("Addition:", a + b)

# Broadcasting
print("Broadcasting with scalar:", a * 3)

Addition: [5 7 9]
Broadcasting with scalar: [3 6 9]


In [ ]:
import numpy as np

# Creating a 1D array
a = np.array([1, 2, 3])

# Adding a scalar value to the array
result = a + 5

print("Original Array:", a)
print("After Adding 5:", result)

Original Array: [1 2 3]
After Adding 5: [6 7 8]


In [ ]:
import numpy as np

# Creating a 1D array and a 2D array
a = np.array([0, 1, 2])
b = np.array([[0, 1, 2], [3, 4, 5]])

# Adding the 1D array to each row of the 2D array
result = a + b

print("1D Array:", a)
print("2D Array:", b)
print("Broadcasted Addition:", result)

1D Array: [0 1 2]
2D Array: [[0 1 2]
 [3 4 5]]
Broadcasted Addition: [[0 2 4]
 [3 5 7]]


In [ ]:
import numpy as np

# Creating two arrays
a = np.array([[1], [2], [3]])
b = np.array([1, 2, 3])

# Adding the two arrays
result = a + b

print("Array a:", a)
print("Array b:", b)
print("Broadcasted Addition:", result)

Array a: [[1]
 [2]
 [3]]
Array b: [1 2 3]
Broadcasted Addition: [[2 3 4]
 [3 4 5]
 [4 5 6]]


In [ ]:
import numpy as np

# Creating two incompatible arrays
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([1, 2])

try:
    result = a + b
except ValueError as e:
    print("Error:", e)

Error: operands could not be broadcast together with shapes (2,3) (2,) 


In [ ]:
# broadcast only if the rows of the second array is same amount as number of columns of the first

In [ ]:
a.shape

(2, 3)

In [ ]:
b.shape

(2,)

In [ ]:

import numpy as np

# Creating a 2D array and a 1D array
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([1, 2, 3])

# Element-wise multiplication
result = a * b
print("2D Array:", a)
print("1D Array:", b)
print("Broadcasted Multiplication:", result)

2D Array: [[1 2 3]
 [4 5 6]]
1D Array: [1 2 3]
Broadcasted Multiplication: [[ 1  4  9]
 [ 4 10 18]]


In [ ]:
# Creating a sample array
array = np.array([[1, 2, 3], [4, 5, 6]])

# Sum of all elements
print("Sum:", np.sum(array))

# Mean value
print("Mean:", np.mean(array))

# Minimum and Maximum
print("Min:", np.min(array), "Max:", np.max(array))

Sum: 21
Mean: 3.5
Min: 1 Max: 6


In [ ]:
from PIL import Image
import numpy as np
image = Image.open('soldier.png', )
arr = np.array(image)
arr

UnidentifiedImageError: cannot identify image file 'soldier.png'

In [ ]:
import numpy as np

# Creating a 1D array
array = np.arange(1, 10)  # Array of numbers from 1 to 9

# Reshaping to a 3x3 matrix
reshaped_array = array.reshape(3, 3)
print("Reshaped to 3x3:\n", reshaped_array)

Reshaped to 3x3:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
# Transposing the reshaped array
transposed_array = reshaped_array.T
print("Transposed array:\n", transposed_array)

Transposed array:
 [[1 4 7]
 [2 5 8]
 [3 6 9]]


In [ ]:
# Aggregating data after reshaping
data = np.random.rand(6, 2)
reshaped_data = data.reshape(3, 4)
mean_values = np.mean(reshaped_data, axis=1)  # Mean of each reshaped group
print(data)

print(reshaped_data)


print("Mean values:", mean_values)

[[0.69459741 0.3052498 ]
 [0.04906612 0.64988569]
 [0.53281665 0.41820181]
 [0.52880759 0.01030917]
 [0.30329806 0.08079601]
 [0.78249611 0.29950748]]
[[0.69459741 0.3052498  0.04906612 0.64988569]
 [0.53281665 0.41820181 0.52880759 0.01030917]
 [0.30329806 0.08079601 0.78249611 0.29950748]]
Mean values: [0.42469976 0.3725338  0.36652441]


In [ ]:
# 1. Reshape Array: Create a 1D array with 12 elements and reshape it to a 4x3 matrix. Then reshape it to a 2x6 matrix.

# 2. Transpose Matrix: Transpose the 2x6 matrix you created in the previous step.

# 3. Combine Reshaping and Transposing: Create a 3x4 matrix, transpose it, and then reshape the transposed matrix to a 1D array.